# packages in environment at /Users/williamhbelew/opt/anaconda3/envs/43_practice_env:
#
# Name                    Version                   Build  Channel
beautifulsoup4            4.12.2          py310hecd8cb5_0  
blas                      1.0                         mkl  
brotlipy                  0.7.0           py310hca72f7f_1002  
bs4                       4.12.2           py38hd3eb1b0_0  
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2023.05.30           hecd8cb5_0  
certifi                   2023.7.22       py310hecd8cb5_0  
cffi                      1.15.1          py310h6c40b1e_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4           py310hecd8cb5_0  
cryptography              41.0.2          py310h3b477ad_0  
emoji                     2.8.0                    pypi_0    pypi
icu                       73.1                 hcec6c5f_0  
idna                      3.4             py310hecd8cb5_0  
intel-openmp              2023.1.0         ha357a0b_43547  
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0           py310hecd8cb5_0  
libcxx                    14.0.6               h9765a3e_0  
libffi                    3.4.4                hecd8cb5_0  
libiconv                  1.16                 hca72f7f_2  
libxml2                   2.10.4               h1bd7e62_1  
libxslt                   1.1.37               h6c40b1e_1  
lxml                      4.9.2           py310h6c40b1e_0  
markdown                  3.4.4                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
mkl                       2023.1.0         h8e150cf_43559  
mkl-service               2.4.0           py310h6c40b1e_1  
mkl_fft                   1.3.6           py310h3ea8b11_1  
mkl_random                1.2.2           py310h3ea8b11_1  
ncurses                   6.4                  hcec6c5f_0  
nltk                      3.8.1           py310hecd8cb5_0  
numpy                     1.25.2          py310h827a554_0  
numpy-base                1.25.2          py310ha186be2_0  
openssl                   3.0.10               hca72f7f_2  
pint                      0.22                     pypi_0    pypi
pip                       23.2.1          py310hecd8cb5_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 23.2.0          py310hecd8cb5_0  
pysocks                   1.7.1           py310hecd8cb5_0  
python                    3.10.12              h5ee71fb_0  
readline                  8.2                  hca72f7f_0  
regex                     2022.7.9        py310hca72f7f_0  
requests                  2.31.0          py310hecd8cb5_0  
setuptools                68.0.0          py310hecd8cb5_0  
soupsieve                 2.4             py310hecd8cb5_0  
sqlite                    3.41.2               h6c40b1e_0  
tbb                       2021.8.0             ha357a0b_0  
tk                        8.6.12               h5d9f67b_0  
tqdm                      4.65.0          py310h20db666_0  
typing-extensions         4.7.1                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.16         py310hecd8cb5_0  
wheel                     0.38.4          py310hecd8cb5_0  
xz                        5.4.2                h6c40b1e_0  
zlib                      1.2.13               h4dc903c_0  
